-- 01_provision.sql: CGFS Improper Payment Prevention Demo — Infrastructure Setup
-- Run as ACCOUNTADMIN to create role and initial objects, then transfer ownership.

USE ROLE ACCOUNTADMIN;

-- 1. Create custom demo role
CREATE ROLE IF NOT EXISTS CGFS_DEMO_ROLE
  COMMENT = 'Custom role for CGFS Improper Payment Prevention Demo';

-- Grant role to SYSADMIN (hierarchy) and to the demo operator
GRANT ROLE CGFS_DEMO_ROLE TO ROLE SYSADMIN;
GRANT ROLE CGFS_DEMO_ROLE TO USER EENGLER;

-- 2. Create warehouse
CREATE WAREHOUSE IF NOT EXISTS CGFS_DEMO_WH
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Compute for CGFS Fraud Demo workloads';

GRANT USAGE ON WAREHOUSE CGFS_DEMO_WH TO ROLE CGFS_DEMO_ROLE;
GRANT OPERATE ON WAREHOUSE CGFS_DEMO_WH TO ROLE CGFS_DEMO_ROLE;

-- 3. Create database and schemas
CREATE DATABASE IF NOT EXISTS CGFS_FRAUD_DEMO
  COMMENT = 'CGFS Improper Payment Prevention Demo — Synthetic Data';

GRANT OWNERSHIP ON DATABASE CGFS_FRAUD_DEMO TO ROLE CGFS_DEMO_ROLE COPY CURRENT GRANTS;

USE DATABASE CGFS_FRAUD_DEMO;

-- Drop the auto-created PUBLIC schema ownership transfer, create our schemas
GRANT OWNERSHIP ON SCHEMA CGFS_FRAUD_DEMO.PUBLIC TO ROLE CGFS_DEMO_ROLE COPY CURRENT GRANTS;

CREATE SCHEMA IF NOT EXISTS CGFS_FRAUD_DEMO.RAW
  COMMENT = 'Raw synthetic data from GFMS, RFMS, GFACS, gTA';
GRANT OWNERSHIP ON SCHEMA CGFS_FRAUD_DEMO.RAW TO ROLE CGFS_DEMO_ROLE COPY CURRENT GRANTS;

CREATE SCHEMA IF NOT EXISTS CGFS_FRAUD_DEMO.ANALYTICS
  COMMENT = 'Analytics pipeline: rules engine, ML scoring, risk summaries';
GRANT OWNERSHIP ON SCHEMA CGFS_FRAUD_DEMO.ANALYTICS TO ROLE CGFS_DEMO_ROLE COPY CURRENT GRANTS;

-- 4. Grant Cortex ML privileges
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CGFS_DEMO_ROLE;

-- 5. Verify setup
USE ROLE CGFS_DEMO_ROLE;
USE WAREHOUSE CGFS_DEMO_WH;
USE DATABASE CGFS_FRAUD_DEMO;

SELECT CURRENT_ROLE() AS ROLE,
       CURRENT_WAREHOUSE() AS WAREHOUSE,
       CURRENT_DATABASE() AS DATABASE_NAME;
