-- 03_analytics_pipeline.sql: Dynamic Tables — Unified View + Rules Engine
-- Run as CGFS_DEMO_ROLE after 02_synthetic_data.sql.

USE ROLE CGFS_DEMO_ROLE;
USE WAREHOUSE CGFS_DEMO_WH;
USE DATABASE CGFS_FRAUD_DEMO;

----------------------------------------------------------------------
-- 1. UNIFIED_TRANSACTIONS — merges GFMS + RFMS into single view
----------------------------------------------------------------------

CREATE OR REPLACE DYNAMIC TABLE ANALYTICS.UNIFIED_TRANSACTIONS
  TARGET_LAG = '1 hour'
  WAREHOUSE = CGFS_DEMO_WH
AS
SELECT
    g.TRANSACTION_ID, 'GFMS' AS SOURCE_SYSTEM, g.OBLIGATION_ID, g.APPROPRIATION_CODE,
    g.VENDOR_ID, g.VENDOR_NAME, g.PAYMENT_AMOUNT, g.OBLIGATION_CEILING,
    g.DISBURSEMENT_DATE, g.DESCRIPTION, g.CONTRACT_ID, g.BUREAU_CODE,
    NULL AS POST_ID, NULL AS CURRENCY_CODE
FROM RAW.GFMS_TRANSACTIONS g
UNION ALL
SELECT
    r.TRANSACTION_ID, 'RFMS' AS SOURCE_SYSTEM, r.OBLIGATION_ID, NULL AS APPROPRIATION_CODE,
    r.VENDOR_ID, r.VENDOR_NAME, r.PAYMENT_AMOUNT, g_obl.OBLIGATION_CEILING,
    r.DISBURSEMENT_DATE, r.DESCRIPTION, r.CONTRACT_ID, NULL AS BUREAU_CODE,
    r.POST_ID, r.CURRENCY_CODE
FROM RAW.RFMS_TRANSACTIONS r
LEFT JOIN (
    SELECT OBLIGATION_ID, MAX(OBLIGATION_CEILING) AS OBLIGATION_CEILING
    FROM RAW.GFMS_TRANSACTIONS GROUP BY OBLIGATION_ID
) g_obl ON r.OBLIGATION_ID = g_obl.OBLIGATION_ID;

----------------------------------------------------------------------
-- 2. RULES_ENGINE_FLAGS — 6 deterministic detection rules
----------------------------------------------------------------------

CREATE OR REPLACE DYNAMIC TABLE ANALYTICS.RULES_ENGINE_FLAGS
  TARGET_LAG = '1 hour'
  WAREHOUSE = CGFS_DEMO_WH
AS
WITH
-- RULE 001: Ghost Employee Payments
ghost_employee AS (
    SELECT ut.TRANSACTION_ID, 'RULE_001' AS RULE_ID, 'Ghost Employee Payment' AS RULE_NAME,
        'PAYROLL_FRAUD' AS RULE_CATEGORY,
        CASE WHEN DATEDIFF(DAY, p.SEPARATION_DATE, ut.DISBURSEMENT_DATE) > 90 THEN 'CRITICAL'
             WHEN DATEDIFF(DAY, p.SEPARATION_DATE, ut.DISBURSEMENT_DATE) > 30 THEN 'HIGH'
             ELSE 'MEDIUM' END AS SEVERITY,
        LEAST(1.0, 0.7 + (DATEDIFF(DAY, p.SEPARATION_DATE, ut.DISBURSEMENT_DATE) / 365.0) * 0.3) AS CONFIDENCE,
        ut.PAYMENT_AMOUNT AS ESTIMATED_IMPROPER_AMOUNT,
        'Payment of $' || TO_VARCHAR(ut.PAYMENT_AMOUNT, '999,999,999.99') || ' to ' || ut.VENDOR_NAME ||
        ' (Employee ' || p.EMPLOYEE_ID || ') on ' || TO_VARCHAR(ut.DISBURSEMENT_DATE, 'MM/DD/YYYY') ||
        ', but employee was separated on ' || TO_VARCHAR(p.SEPARATION_DATE, 'MM/DD/YYYY') ||
        ' (' || DATEDIFF(DAY, p.SEPARATION_DATE, ut.DISBURSEMENT_DATE) || ' days after separation).' AS EXPLANATION
    FROM ANALYTICS.UNIFIED_TRANSACTIONS ut
    JOIN (SELECT DISTINCT EMPLOYEE_ID, EMPLOYEE_NAME, SEPARATION_DATE FROM RAW.GFACS_PAYROLL WHERE SEPARATION_DATE IS NOT NULL) p
        ON ut.VENDOR_ID = p.EMPLOYEE_ID
    WHERE ut.DISBURSEMENT_DATE > p.SEPARATION_DATE
),
-- RULE 002: Cross-Boundary Duplicate Payments
cross_boundary AS (
    SELECT g.TRANSACTION_ID, 'RULE_002' AS RULE_ID, 'Cross-Boundary Duplicate Payment' AS RULE_NAME,
        'DUPLICATE_PAYMENT' AS RULE_CATEGORY,
        CASE WHEN ABS(g.PAYMENT_AMOUNT - r.PAYMENT_AMOUNT) / NULLIF(g.PAYMENT_AMOUNT, 0) < 0.03 THEN 'CRITICAL'
             WHEN ABS(g.PAYMENT_AMOUNT - r.PAYMENT_AMOUNT) / NULLIF(g.PAYMENT_AMOUNT, 0) < 0.07 THEN 'HIGH'
             ELSE 'MEDIUM' END AS SEVERITY,
        ROUND(1.0 - ABS(g.PAYMENT_AMOUNT - r.PAYMENT_AMOUNT) / NULLIF(GREATEST(g.PAYMENT_AMOUNT, r.PAYMENT_AMOUNT), 0), 3) AS CONFIDENCE,
        g.PAYMENT_AMOUNT AS ESTIMATED_IMPROPER_AMOUNT,
        'Potential duplicate: GFMS $' || TO_VARCHAR(g.PAYMENT_AMOUNT, '999,999,999.99') ||
        ' on ' || TO_VARCHAR(g.DISBURSEMENT_DATE, 'MM/DD/YYYY') ||
        ' to ' || g.VENDOR_ID || ' (' || g.VENDOR_NAME || ')' ||
        ' matches RFMS $' || TO_VARCHAR(r.PAYMENT_AMOUNT, '999,999,999.99') ||
        ' on ' || TO_VARCHAR(r.DISBURSEMENT_DATE, 'MM/DD/YYYY') ||
        ' at ' || r.POST_ID || '. Virtual Merge cannot catch cross-system duplicates.' AS EXPLANATION
    FROM RAW.GFMS_TRANSACTIONS g
    JOIN RAW.RFMS_TRANSACTIONS r ON g.VENDOR_ID = r.VENDOR_ID
        AND ABS(DATEDIFF(DAY, g.DISBURSEMENT_DATE, r.DISBURSEMENT_DATE)) <= 7
        AND ABS(g.PAYMENT_AMOUNT - r.PAYMENT_AMOUNT) / NULLIF(GREATEST(g.PAYMENT_AMOUNT, r.PAYMENT_AMOUNT), 0) <= 0.10
),
-- RULE 003: Over-Obligation Payments (GFMS only)
over_obligation AS (
    SELECT ut.TRANSACTION_ID, 'RULE_003' AS RULE_ID, 'Over-Obligation Payment' AS RULE_NAME,
        'OBLIGATION_BREACH' AS RULE_CATEGORY,
        CASE WHEN running.CUMULATIVE_TOTAL > ut.OBLIGATION_CEILING * 1.20 THEN 'CRITICAL'
             WHEN running.CUMULATIVE_TOTAL > ut.OBLIGATION_CEILING * 1.05 THEN 'HIGH'
             ELSE 'MEDIUM' END AS SEVERITY,
        ROUND(LEAST(1.0, (running.CUMULATIVE_TOTAL - ut.OBLIGATION_CEILING) / NULLIF(ut.OBLIGATION_CEILING, 0)), 3) AS CONFIDENCE,
        ROUND(running.CUMULATIVE_TOTAL - ut.OBLIGATION_CEILING, 2) AS ESTIMATED_IMPROPER_AMOUNT,
        'Obligation ' || ut.OBLIGATION_ID || ' ceiling $' || TO_VARCHAR(ut.OBLIGATION_CEILING, '999,999,999.99') ||
        ' exceeded — cumulative payments $' || TO_VARCHAR(running.CUMULATIVE_TOTAL, '999,999,999.99') ||
        ' (' || ROUND((running.CUMULATIVE_TOTAL - ut.OBLIGATION_CEILING) / NULLIF(ut.OBLIGATION_CEILING, 0) * 100, 1) || '% over).' AS EXPLANATION
    FROM ANALYTICS.UNIFIED_TRANSACTIONS ut
    JOIN (
        SELECT TRANSACTION_ID, OBLIGATION_ID,
               SUM(PAYMENT_AMOUNT) OVER (PARTITION BY OBLIGATION_ID ORDER BY DISBURSEMENT_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE_TOTAL
        FROM ANALYTICS.UNIFIED_TRANSACTIONS
        WHERE SOURCE_SYSTEM = 'GFMS' AND OBLIGATION_CEILING IS NOT NULL AND OBLIGATION_CEILING > 0
    ) running ON ut.TRANSACTION_ID = running.TRANSACTION_ID AND ut.OBLIGATION_ID = running.OBLIGATION_ID
    WHERE ut.SOURCE_SYSTEM = 'GFMS' AND ut.OBLIGATION_CEILING IS NOT NULL AND ut.OBLIGATION_CEILING > 0
      AND running.CUMULATIVE_TOTAL > ut.OBLIGATION_CEILING
),
-- RULE 004: Time/Pay Mismatch
time_pay_mismatch AS (
    SELECT pay.PAYROLL_ID AS TRANSACTION_ID, 'RULE_004' AS RULE_ID, 'Time/Pay Mismatch' AS RULE_NAME,
        'TIME_PAY_MISMATCH' AS RULE_CATEGORY,
        CASE WHEN leave_pct.LEAVE_RATIO > 0.80 THEN 'HIGH' ELSE 'MEDIUM' END AS SEVERITY,
        ROUND(leave_pct.LEAVE_RATIO, 3) AS CONFIDENCE,
        pay.GROSS_PAY AS ESTIMATED_IMPROPER_AMOUNT,
        'Employee ' || pay.EMPLOYEE_ID || ' (' || pay.EMPLOYEE_NAME || ') full pay $' ||
        TO_VARCHAR(pay.GROSS_PAY, '999,999.99') || ' for ' ||
        TO_VARCHAR(pay.PAY_PERIOD_START, 'MM/DD/YYYY') || '-' || TO_VARCHAR(pay.PAY_PERIOD_END, 'MM/DD/YYYY') ||
        ' but on leave ' || ROUND(leave_pct.LEAVE_RATIO * 100, 0) || '% of working days.' AS EXPLANATION
    FROM RAW.GFACS_PAYROLL pay
    JOIN (
        SELECT EMPLOYEE_ID, DATE_TRUNC('MONTH', RECORD_DATE) AS MTH,
               MIN(RECORD_DATE) AS PERIOD_START, MAX(RECORD_DATE) AS PERIOD_END,
               COUNT(CASE WHEN STATUS_CODE IN ('ANNUAL_LEAVE','SICK_LEAVE','LWOP') THEN 1 END)::FLOAT / NULLIF(COUNT(*), 0) AS LEAVE_RATIO
        FROM RAW.GTA_TIME_ATTENDANCE GROUP BY EMPLOYEE_ID, DATE_TRUNC('MONTH', RECORD_DATE) HAVING LEAVE_RATIO > 0.50
    ) leave_pct ON pay.EMPLOYEE_ID = leave_pct.EMPLOYEE_ID
        AND pay.PAY_PERIOD_START <= leave_pct.PERIOD_END AND pay.PAY_PERIOD_END >= leave_pct.PERIOD_START
    WHERE pay.EMPLOYMENT_STATUS = 'ACTIVE' AND pay.GROSS_PAY > 0
),
-- RULE 005: Debarred Vendor
debarred_vendor AS (
    SELECT ut.TRANSACTION_ID, 'RULE_005' AS RULE_ID, 'Payment to Debarred Vendor' AS RULE_NAME,
        'VENDOR_RISK' AS RULE_CATEGORY, 'CRITICAL' AS SEVERITY, 1.0 AS CONFIDENCE,
        ut.PAYMENT_AMOUNT AS ESTIMATED_IMPROPER_AMOUNT,
        'Payment $' || TO_VARCHAR(ut.PAYMENT_AMOUNT, '999,999,999.99') ||
        ' to debarred vendor ' || dv.VENDOR_NAME || ' (' || dv.VENDOR_ID ||
        '). Debarred ' || TO_VARCHAR(dv.DEBARMENT_DATE, 'MM/DD/YYYY') || ': ' || dv.REASON || '.' AS EXPLANATION
    FROM ANALYTICS.UNIFIED_TRANSACTIONS ut
    JOIN RAW.DEBARRED_VENDORS dv ON ut.VENDOR_ID = dv.VENDOR_ID
    WHERE ut.DISBURSEMENT_DATE >= dv.DEBARMENT_DATE
),
-- RULE 006: Split Payment Pattern
split_payment AS (
    SELECT ut.TRANSACTION_ID, 'RULE_006' AS RULE_ID, 'Split Payment Pattern' AS RULE_NAME,
        'SPLIT_PAYMENT' AS RULE_CATEGORY,
        CASE WHEN ss.PAYMENT_COUNT >= 5 THEN 'HIGH' WHEN ss.PAYMENT_COUNT >= 3 THEN 'MEDIUM' ELSE 'LOW' END AS SEVERITY,
        ROUND(LEAST(1.0, ss.PAYMENT_COUNT / 5.0), 3) AS CONFIDENCE,
        ut.PAYMENT_AMOUNT AS ESTIMATED_IMPROPER_AMOUNT,
        'Obligation ' || ut.OBLIGATION_ID || ': ' || ss.PAYMENT_COUNT ||
        ' payments avg $' || TO_VARCHAR(ss.AVG_PAYMENT, '999,999.99') ||
        ' totaling $' || TO_VARCHAR(ss.TOTAL_PAYMENTS, '999,999,999.99') ||
        '. Cluster below $' || CASE WHEN ss.AVG_PAYMENT < 10000 THEN '10,000' ELSE '25,000' END || ' threshold.' AS EXPLANATION
    FROM ANALYTICS.UNIFIED_TRANSACTIONS ut
    JOIN (
        SELECT OBLIGATION_ID, COUNT(*) AS PAYMENT_COUNT, AVG(PAYMENT_AMOUNT) AS AVG_PAYMENT,
               MIN(PAYMENT_AMOUNT) AS MIN_PAYMENT, MAX(PAYMENT_AMOUNT) AS MAX_PAYMENT, SUM(PAYMENT_AMOUNT) AS TOTAL_PAYMENTS
        FROM ANALYTICS.UNIFIED_TRANSACTIONS GROUP BY OBLIGATION_ID
        HAVING COUNT(*) >= 3 AND MAX(PAYMENT_AMOUNT) < 10000 AND SUM(PAYMENT_AMOUNT) > 25000
           AND (MAX(PAYMENT_AMOUNT) - MIN(PAYMENT_AMOUNT)) / NULLIF(AVG(PAYMENT_AMOUNT), 0) < 0.3
    ) ss ON ut.OBLIGATION_ID = ss.OBLIGATION_ID
)
-- Combine all rules
SELECT TRANSACTION_ID, RULE_ID, RULE_NAME, RULE_CATEGORY, SEVERITY, CONFIDENCE, ESTIMATED_IMPROPER_AMOUNT, EXPLANATION, CURRENT_TIMESTAMP() AS FLAGGED_AT FROM ghost_employee
UNION ALL SELECT *, CURRENT_TIMESTAMP() FROM cross_boundary
UNION ALL SELECT *, CURRENT_TIMESTAMP() FROM over_obligation
UNION ALL SELECT *, CURRENT_TIMESTAMP() FROM time_pay_mismatch
UNION ALL SELECT *, CURRENT_TIMESTAMP() FROM debarred_vendor
UNION ALL SELECT *, CURRENT_TIMESTAMP() FROM split_payment;
