-- 05_summary_tables.sql: Combined Risk Summary + 4 Aggregate Tables
-- Run as CGFS_DEMO_ROLE after 04_ml_anomaly.sql.

USE ROLE CGFS_DEMO_ROLE;
USE WAREHOUSE CGFS_DEMO_WH;
USE DATABASE CGFS_FRAUD_DEMO;

----------------------------------------------------------------------
-- 1. FRAUD_RISK_SUMMARY — combined risk score from rules + ML
----------------------------------------------------------------------

CREATE OR REPLACE TABLE ANALYTICS.FRAUD_RISK_SUMMARY AS
WITH rule_flags AS (
    SELECT TRANSACTION_ID,
           MAX(CASE SEVERITY WHEN 'CRITICAL' THEN 4 WHEN 'HIGH' THEN 3 WHEN 'MEDIUM' THEN 2 ELSE 1 END) AS MAX_SEVERITY_NUM,
           MAX(CONFIDENCE) AS MAX_CONFIDENCE,
           SUM(ESTIMATED_IMPROPER_AMOUNT) AS RULES_IMPROPER_AMT,
           ARRAY_AGG(OBJECT_CONSTRUCT('rule_id', RULE_ID, 'rule_name', RULE_NAME, 'severity', SEVERITY, 'category', RULE_CATEGORY)) AS RULE_FLAGS
    FROM ANALYTICS.RULES_ENGINE_FLAGS GROUP BY TRANSACTION_ID
),
ml_flags AS (
    SELECT TRANSACTION_ID, ANOMALY_SCORE,
           CASE ANOMALY_SEVERITY WHEN 'CRITICAL' THEN 4 WHEN 'HIGH' THEN 3 WHEN 'MEDIUM' THEN 2 ELSE 1 END AS ML_SEVERITY_NUM,
           PAYMENT_AMOUNT AS ML_IMPROPER_AMT
    FROM ANALYTICS.ML_ANOMALY_FLAGS
),
combined AS (
    SELECT ut.TRANSACTION_ID, ut.SOURCE_SYSTEM, ut.VENDOR_ID, ut.VENDOR_NAME,
           ut.PAYMENT_AMOUNT, ut.DISBURSEMENT_DATE, ut.OBLIGATION_ID, ut.POST_ID,
           rf.MAX_SEVERITY_NUM, rf.MAX_CONFIDENCE, rf.RULES_IMPROPER_AMT, rf.RULE_FLAGS,
           mf.ANOMALY_SCORE, mf.ML_SEVERITY_NUM, mf.ML_IMPROPER_AMT,
           ROUND(LEAST(100,
               COALESCE(rf.MAX_SEVERITY_NUM * 20, 0) + COALESCE(rf.MAX_CONFIDENCE * 15, 0) +
               COALESCE(mf.ANOMALY_SCORE * 5, 0) +
               CASE WHEN rf.TRANSACTION_ID IS NOT NULL AND mf.TRANSACTION_ID IS NOT NULL THEN 15 ELSE 0 END
           ), 1) AS RISK_SCORE
    FROM ANALYTICS.UNIFIED_TRANSACTIONS ut
    LEFT JOIN rule_flags rf ON ut.TRANSACTION_ID = rf.TRANSACTION_ID
    LEFT JOIN ml_flags mf ON ut.TRANSACTION_ID = mf.TRANSACTION_ID
    WHERE rf.TRANSACTION_ID IS NOT NULL OR mf.TRANSACTION_ID IS NOT NULL
)
SELECT TRANSACTION_ID, SOURCE_SYSTEM, VENDOR_ID, VENDOR_NAME, PAYMENT_AMOUNT,
       DISBURSEMENT_DATE, OBLIGATION_ID, POST_ID, RISK_SCORE,
       CASE WHEN RISK_SCORE >= 80 THEN 'CRITICAL' WHEN RISK_SCORE >= 60 THEN 'HIGH'
            WHEN RISK_SCORE >= 40 THEN 'MEDIUM' ELSE 'LOW' END AS RISK_TIER,
       COALESCE(RULE_FLAGS, ARRAY_CONSTRUCT()) AS FLAGS,
       COALESCE(RULES_IMPROPER_AMT, 0) + COALESCE(ML_IMPROPER_AMT, 0) AS TOTAL_ESTIMATED_LOSS,
       CASE WHEN RISK_SCORE >= 80 THEN 'BLOCK' WHEN RISK_SCORE >= 60 THEN 'REVIEW'
            WHEN RISK_SCORE >= 40 THEN 'MONITOR' ELSE 'PASS' END AS RECOMMENDED_ACTION,
       ANOMALY_SCORE AS ML_ANOMALY_SCORE
FROM combined;

----------------------------------------------------------------------
-- 2. FRAUD_SUMMARY_BY_CATEGORY
----------------------------------------------------------------------

CREATE OR REPLACE TABLE ANALYTICS.FRAUD_SUMMARY_BY_CATEGORY AS
SELECT r.RULE_CATEGORY AS FRAUD_CATEGORY, r.RULE_NAME,
       COUNT(DISTINCT r.TRANSACTION_ID) AS FLAG_COUNT,
       ROUND(SUM(r.ESTIMATED_IMPROPER_AMOUNT), 2) AS TOTAL_EXPOSURE,
       ROUND(AVG(r.ESTIMATED_IMPROPER_AMOUNT), 2) AS AVG_AMOUNT,
       COUNT(DISTINCT CASE WHEN r.SEVERITY = 'CRITICAL' THEN r.TRANSACTION_ID END) AS CRITICAL_COUNT,
       COUNT(DISTINCT CASE WHEN r.SEVERITY = 'HIGH' THEN r.TRANSACTION_ID END) AS HIGH_COUNT
FROM ANALYTICS.RULES_ENGINE_FLAGS r GROUP BY r.RULE_CATEGORY, r.RULE_NAME;

----------------------------------------------------------------------
-- 3. FRAUD_SUMMARY_BY_POST
----------------------------------------------------------------------

CREATE OR REPLACE TABLE ANALYTICS.FRAUD_SUMMARY_BY_POST AS
SELECT COALESCE(frs.POST_ID, 'DOMESTIC') AS POST_ID, frs.SOURCE_SYSTEM,
       COUNT(*) AS FLAG_COUNT, ROUND(SUM(frs.TOTAL_ESTIMATED_LOSS), 2) AS TOTAL_EXPOSURE,
       ROUND(AVG(frs.TOTAL_ESTIMATED_LOSS), 2) AS AVG_EXPOSURE,
       COUNT(CASE WHEN frs.RISK_TIER = 'CRITICAL' THEN 1 END) AS CRITICAL_COUNT
FROM ANALYTICS.FRAUD_RISK_SUMMARY frs GROUP BY 1, 2;

----------------------------------------------------------------------
-- 4. FRAUD_SUMMARY_BY_VENDOR
----------------------------------------------------------------------

CREATE OR REPLACE TABLE ANALYTICS.FRAUD_SUMMARY_BY_VENDOR AS
SELECT frs.VENDOR_ID, frs.VENDOR_NAME, COUNT(*) AS FLAG_COUNT,
       ROUND(SUM(frs.TOTAL_ESTIMATED_LOSS), 2) AS TOTAL_EXPOSURE,
       COUNT(DISTINCT frs.SOURCE_SYSTEM) AS SYSTEMS_INVOLVED,
       MAX(frs.RISK_TIER) AS HIGHEST_RISK_TIER,
       ARRAY_AGG(DISTINCT frs.RISK_TIER) AS RISK_TIERS
FROM ANALYTICS.FRAUD_RISK_SUMMARY frs GROUP BY 1, 2;

----------------------------------------------------------------------
-- 5. FRAUD_TREND_MONTHLY
----------------------------------------------------------------------

CREATE OR REPLACE TABLE ANALYTICS.FRAUD_TREND_MONTHLY AS
SELECT DATE_TRUNC('MONTH', frs.DISBURSEMENT_DATE)::DATE AS TREND_MONTH,
       COALESCE(r.RULE_CATEGORY, 'ML_ANOMALY') AS FRAUD_CATEGORY,
       COUNT(DISTINCT frs.TRANSACTION_ID) AS FLAG_COUNT,
       ROUND(SUM(frs.TOTAL_ESTIMATED_LOSS), 2) AS TOTAL_EXPOSURE
FROM ANALYTICS.FRAUD_RISK_SUMMARY frs
LEFT JOIN ANALYTICS.RULES_ENGINE_FLAGS r ON frs.TRANSACTION_ID = r.TRANSACTION_ID
GROUP BY 1, 2 ORDER BY 1;
