-- 08_data_exploration.sql: Interactive Data Exploration Walkthrough
-- Run each section interactively during a demo.

USE ROLE CGFS_DEMO_ROLE;
USE WAREHOUSE CGFS_DEMO_WH;
USE DATABASE CGFS_FRAUD_DEMO;

-- ============================================================================
-- SECTION 1: Raw Data Overview
-- ============================================================================

-- 1.1 Table row counts
SELECT 'GFMS_TRANSACTIONS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW.GFMS_TRANSACTIONS
UNION ALL SELECT 'RFMS_TRANSACTIONS', COUNT(*) FROM RAW.RFMS_TRANSACTIONS
UNION ALL SELECT 'GFACS_PAYROLL', COUNT(*) FROM RAW.GFACS_PAYROLL
UNION ALL SELECT 'GTA_TIME_ATTENDANCE', COUNT(*) FROM RAW.GTA_TIME_ATTENDANCE
UNION ALL SELECT 'DEBARRED_VENDORS', COUNT(*) FROM RAW.DEBARRED_VENDORS
ORDER BY ROW_COUNT DESC;

-- 1.2 GFMS: Domestic disbursement distribution by appropriation
SELECT APPROPRIATION_CODE, COUNT(*) AS TXN_COUNT,
       ROUND(AVG(PAYMENT_AMOUNT), 2) AS AVG_AMOUNT,
       ROUND(MIN(PAYMENT_AMOUNT), 2) AS MIN_AMOUNT,
       ROUND(MAX(PAYMENT_AMOUNT), 2) AS MAX_AMOUNT,
       ROUND(SUM(PAYMENT_AMOUNT), 2) AS TOTAL_AMOUNT
FROM RAW.GFMS_TRANSACTIONS GROUP BY APPROPRIATION_CODE ORDER BY TOTAL_AMOUNT DESC;

-- 1.3 RFMS: Overseas disbursements by post
SELECT POST_ID, CURRENCY_CODE, COUNT(*) AS TXN_COUNT,
       ROUND(AVG(PAYMENT_AMOUNT), 2) AS AVG_AMOUNT,
       ROUND(SUM(PAYMENT_AMOUNT), 2) AS TOTAL_AMOUNT
FROM RAW.RFMS_TRANSACTIONS GROUP BY POST_ID, CURRENCY_CODE ORDER BY TOTAL_AMOUNT DESC;

-- 1.4 Employee workforce snapshot
SELECT STAFF_TYPE, EMPLOYMENT_STATUS, COUNT(DISTINCT EMPLOYEE_ID) AS EMPLOYEE_COUNT
FROM RAW.GFACS_PAYROLL GROUP BY STAFF_TYPE, EMPLOYMENT_STATUS ORDER BY STAFF_TYPE, EMPLOYEE_COUNT DESC;

-- 1.5 Separated employees
SELECT DISTINCT EMPLOYEE_ID, EMPLOYEE_NAME, SEPARATION_DATE, EMPLOYMENT_STATUS, POST_ID, GRADE
FROM RAW.GFACS_PAYROLL WHERE SEPARATION_DATE IS NOT NULL ORDER BY SEPARATION_DATE DESC LIMIT 20;

-- 1.6 Debarred vendors
SELECT * FROM RAW.DEBARRED_VENDORS ORDER BY DEBARMENT_DATE DESC;

-- ============================================================================
-- SECTION 2: Unified Transaction View
-- ============================================================================

-- 2.1 Volume by source system
SELECT SOURCE_SYSTEM, COUNT(*) AS TXN_COUNT,
       ROUND(SUM(PAYMENT_AMOUNT), 2) AS TOTAL_AMOUNT,
       ROUND(AVG(PAYMENT_AMOUNT), 2) AS AVG_AMOUNT
FROM ANALYTICS.UNIFIED_TRANSACTIONS GROUP BY SOURCE_SYSTEM;

-- 2.2 Payment amount distribution
SELECT
    CASE WHEN PAYMENT_AMOUNT < 5000 THEN '< $5K'
         WHEN PAYMENT_AMOUNT < 10000 THEN '$5K - $10K'
         WHEN PAYMENT_AMOUNT < 25000 THEN '$10K - $25K'
         WHEN PAYMENT_AMOUNT < 50000 THEN '$25K - $50K'
         WHEN PAYMENT_AMOUNT < 100000 THEN '$50K - $100K'
         WHEN PAYMENT_AMOUNT < 250000 THEN '$100K - $250K'
         ELSE '$250K+' END AS AMOUNT_BUCKET,
    COUNT(*) AS TXN_COUNT,
    ROUND(SUM(PAYMENT_AMOUNT), 2) AS TOTAL_AMOUNT
FROM ANALYTICS.UNIFIED_TRANSACTIONS GROUP BY 1 ORDER BY MIN(PAYMENT_AMOUNT);

-- 2.3 Monthly transaction volume
SELECT DATE_TRUNC('MONTH', DISBURSEMENT_DATE)::DATE AS MONTH, SOURCE_SYSTEM,
       COUNT(*) AS TXN_COUNT, ROUND(SUM(PAYMENT_AMOUNT), 2) AS TOTAL_AMOUNT
FROM ANALYTICS.UNIFIED_TRANSACTIONS GROUP BY 1, 2 ORDER BY 1, 2;

-- ============================================================================
-- SECTION 3: Rules Engine Results
-- ============================================================================

-- 3.1 Flag summary by rule
SELECT RULE_ID, RULE_NAME, RULE_CATEGORY, COUNT(*) AS FLAG_COUNT,
       TO_VARCHAR(ROUND(SUM(ESTIMATED_IMPROPER_AMOUNT), 2), '$999,999,999.99') AS TOTAL_EXPOSURE,
       ROUND(AVG(ESTIMATED_IMPROPER_AMOUNT), 2) AS AVG_EXPOSURE
FROM ANALYTICS.RULES_ENGINE_FLAGS GROUP BY RULE_ID, RULE_NAME, RULE_CATEGORY
ORDER BY SUM(ESTIMATED_IMPROPER_AMOUNT) DESC;

-- 3.2 Ghost Employee deep dive
SELECT TRANSACTION_ID, EXPLANATION, SEVERITY, ESTIMATED_IMPROPER_AMOUNT, CONFIDENCE
FROM ANALYTICS.RULES_ENGINE_FLAGS WHERE RULE_CATEGORY = 'PAYROLL_FRAUD'
ORDER BY ESTIMATED_IMPROPER_AMOUNT DESC LIMIT 15;

-- 3.3 Cross-Boundary Duplicates — the hero finding
SELECT TRANSACTION_ID, EXPLANATION, SEVERITY, ESTIMATED_IMPROPER_AMOUNT
FROM ANALYTICS.RULES_ENGINE_FLAGS WHERE RULE_CATEGORY = 'DUPLICATE_PAYMENT'
ORDER BY ESTIMATED_IMPROPER_AMOUNT DESC;

-- 3.4 Over-Obligation breaches
SELECT TRANSACTION_ID, EXPLANATION, SEVERITY, ESTIMATED_IMPROPER_AMOUNT
FROM ANALYTICS.RULES_ENGINE_FLAGS WHERE RULE_CATEGORY = 'OBLIGATION_BREACH'
ORDER BY ESTIMATED_IMPROPER_AMOUNT DESC LIMIT 10;

-- 3.5 Debarred vendor payments
SELECT TRANSACTION_ID, EXPLANATION, ESTIMATED_IMPROPER_AMOUNT
FROM ANALYTICS.RULES_ENGINE_FLAGS WHERE RULE_CATEGORY = 'VENDOR_RISK'
ORDER BY ESTIMATED_IMPROPER_AMOUNT DESC;

-- 3.6 Split payment patterns
SELECT TRANSACTION_ID, EXPLANATION, ESTIMATED_IMPROPER_AMOUNT
FROM ANALYTICS.RULES_ENGINE_FLAGS WHERE RULE_CATEGORY = 'SPLIT_PAYMENT'
ORDER BY TRANSACTION_ID LIMIT 20;

-- ============================================================================
-- SECTION 4: ML Anomaly Detection
-- ============================================================================

-- 4.1 ML anomaly summary
SELECT ANOMALY_SEVERITY, COUNT(*) AS ANOMALY_COUNT,
       ROUND(SUM(PAYMENT_AMOUNT), 2) AS TOTAL_AMOUNT,
       ROUND(AVG(ANOMALY_SCORE), 2) AS AVG_ZSCORE,
       ROUND(MAX(ANOMALY_SCORE), 2) AS MAX_ZSCORE
FROM ANALYTICS.ML_ANOMALY_FLAGS GROUP BY ANOMALY_SEVERITY ORDER BY AVG_ZSCORE DESC;

-- 4.2 Top ML-flagged outliers
SELECT TRANSACTION_ID, SOURCE_SYSTEM, VENDOR_NAME, POST_ID,
       TO_VARCHAR(PAYMENT_AMOUNT, '$999,999,999.99') AS AMOUNT,
       ANOMALY_SCORE AS Z_SCORE, ANOMALY_SEVERITY
FROM ANALYTICS.ML_ANOMALY_FLAGS ORDER BY ANOMALY_SCORE DESC LIMIT 15;

-- ============================================================================
-- SECTION 5: Combined Risk Summary
-- ============================================================================

-- 5.1 Risk tier distribution
SELECT RISK_TIER, RECOMMENDED_ACTION, COUNT(*) AS TXN_COUNT,
       TO_VARCHAR(ROUND(SUM(TOTAL_ESTIMATED_LOSS), 2), '$999,999,999.99') AS TOTAL_EXPOSURE
FROM ANALYTICS.FRAUD_RISK_SUMMARY GROUP BY RISK_TIER, RECOMMENDED_ACTION
ORDER BY SUM(TOTAL_ESTIMATED_LOSS) DESC;

-- 5.2 Top 20 highest-risk transactions
SELECT TRANSACTION_ID, VENDOR_NAME, SOURCE_SYSTEM, POST_ID,
       TO_VARCHAR(PAYMENT_AMOUNT, '$999,999,999.99') AS PAYMENT,
       RISK_SCORE, RISK_TIER,
       TO_VARCHAR(TOTAL_ESTIMATED_LOSS, '$999,999,999.99') AS ESTIMATED_LOSS,
       RECOMMENDED_ACTION
FROM ANALYTICS.FRAUD_RISK_SUMMARY ORDER BY RISK_SCORE DESC LIMIT 20;

-- ============================================================================
-- SECTION 6: Aggregate Summaries
-- ============================================================================

SELECT * FROM ANALYTICS.FRAUD_SUMMARY_BY_CATEGORY ORDER BY TOTAL_EXPOSURE DESC;
SELECT * FROM ANALYTICS.FRAUD_SUMMARY_BY_POST ORDER BY TOTAL_EXPOSURE DESC LIMIT 10;

SELECT VENDOR_ID, VENDOR_NAME, FLAG_COUNT,
       TO_VARCHAR(TOTAL_EXPOSURE, '$999,999,999.99') AS EXPOSURE,
       SYSTEMS_INVOLVED, HIGHEST_RISK_TIER
FROM ANALYTICS.FRAUD_SUMMARY_BY_VENDOR ORDER BY TOTAL_EXPOSURE DESC LIMIT 10;

SELECT * FROM ANALYTICS.FRAUD_TREND_MONTHLY ORDER BY TREND_MONTH, FRAUD_CATEGORY;

-- ============================================================================
-- SECTION 7: Prevention Value / ROI
-- ============================================================================

SELECT COUNT(*) AS TOTAL_FLAGGED_TRANSACTIONS,
       TO_VARCHAR(ROUND(SUM(TOTAL_ESTIMATED_LOSS), 2), '$999,999,999.99') AS TOTAL_AT_RISK,
       TO_VARCHAR(ROUND(SUM(TOTAL_ESTIMATED_LOSS) * 1.72, 2), '$999,999,999.99') AS RECOVERY_COST_IF_AFTER_FACT,
       TO_VARCHAR(ROUND(SUM(TOTAL_ESTIMATED_LOSS) * 0.50, 2), '$999,999,999.99') AS LIKELY_RECOVERED_AMOUNT,
       TO_VARCHAR(ROUND(SUM(TOTAL_ESTIMATED_LOSS) - SUM(TOTAL_ESTIMATED_LOSS) * 0.50, 2), '$999,999,999.99') AS NET_LOSS_WITHOUT_PREVENTION
FROM ANALYTICS.FRAUD_RISK_SUMMARY;
